[package]
name = "displex"
version = "0.6.7"
edition = "2021"

[dependencies]
actix-web = "4"
actix-session = { version = "0.7.2", features = ["cookie-session"] }
anyhow = "1.0.71"
chrono = { version = "0.4.24", features = ["serde"] }
clap = { version = "4.3.0", features = ["derive", "env"] }
derive_more = "0.99.17"
dotenvy = "0.15.7"
diesel = { version = "2", features = ["postgres", "r2d2", "chrono"], default-features = false }
diesel_migrations = { version = "2.0.0", features = ["postgres"] }
oauth2 = "4"
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_qs = "0.12.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-actix-web = "0.7.4"
tracing-subscriber = "0.3"
