---
version: v3
services:

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: displex
      POSTGRES_USER: displex
    ports:
      - 5432:5432

  mitm:
    image: mitmproxy/mitmproxy
    restart: always
    ports:
      - 8888:8080
      - 8081:8081
    command:
      - mitmweb
      - --web-host
      - "0.0.0.0"
      - --set 
      - ssl-insecure=true

  cloudflared:
    image: cloudflare/cloudflared:latest
    volumes:
      - $HOME/.cloudflared:/etc/cloudflared
    command:
      - --url 
      - displex:8080 
      - --hostname 
      - displex-dev 
      - --name 
      - displex-dev 
      - --overwrite-dns
      - run

  displex:
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      DISPLEX_DATABASE_URL: postgres://displex:password@postgres/displex
