---
version: v3
services:

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: displex
      POSTGRES_USER: displex
    ports:
      - 5432:5432

  displex:
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      DISPLEX_DATABASE_URL: postgres://displex:password@postgres/displex
      DISPLEX_HOST: "0.0.0.0"
