---
version: v3
services:

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: displex
      POSTGRES_USER: displex
    ports:
      - 5432:5432

  mitm:
    image: mitmproxy/mitmproxy
    tty: true
    ports:
      - 8888:8080
      - 8081:8081
    command: mitmweb --web-host 0.0.0.0

  displex:
    build: .
    ports:
      - 8080:8080
    env_file:
      - server/.env
    environment:
      DISPLEX_DATABASE_URL: postgres://displex:password@postgres/displex
      DISPLEX_HOST: "0.0.0.0"
