---
services:
  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: displex
      POSTGRES_USER: displex
    ports:
      - 5432:5432
