name: CI

# This workflow run tests and build for each push

on:
  push:
    branches:
      - main

jobs:

  test_phaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly          

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version          

      - name: Lint
        run: |
          cd phaser
          cargo fmt -- --check
          cargo clippy -- -D warnings          

      - name: Test
        run: |
          cd phaser
          cargo check
          cargo test --all          

      - name: Build
        run: |
          cd phaser
          cargo build --release 
