name: CI

# This workflow run tests and build for each push

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly
          rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Lint
        run: |
          cd src
          cargo +nightly fmt -- --check
          cargo clippy -- -D warnings

      - name: Test
        run: |
          cd src
          cargo check
          cargo test --all

      - name: Build
        run: |
          cd src
          cargo build --release

  docker-release:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@ecf95283f03858871ff00b787d79c419715afc34 # v2

      - name: Log in to the Container registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get docker image name and build args
        id: required_args
        run: |
          image_name="${{ env.REGISTRY }}/${{ github.actor }}/${{ github.event.repository.name }}"
          image_names="$image_name:${{ github.ref_name }},$image_name:latest"
          # lowercase the name
          image_names=$(echo "$image_names" | tr '[:upper:]' '[:lower:]')
          echo "image_names=$image_names" >> $GITHUB_OUTPUT

      - name: Build and push to ghcr
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4
        with:
          context: .
          push: true
          tags: ${{ steps.required_args.outputs.image_names }}
